disabled_rules:
- force_cast
- function_body_length
- line_length
- trailing_whitespace
- identifier_name

opt_in_rules:
- attributes
- closure_spacing
- empty_count
- explicit_init
- fatal_error_message
- first_where
- implicitly_unwrapped_optional
- missing_docs
- nimble_operator
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- sorted_imports
- switch_case_on_newline
- valid_docs

excluded:
- Carthage/

identifier_name:
  min_length: 2

line_length:
  warning: 200
  error: 250
